### ISSUE TITLE
Find or train decision model for test dataset

### ISSUE THREAD

**Issue by zenna** [zenna/CounterfactualFairness.jl#11]
Counterfactual fairness is relative to both a causal model over the data as well as a decision model which produces the outcome (accepted loan, etc).

We need to either:
- Train a model from scratch
- Find a pre-trained model

**Comment by vollmersj** [comment]
There is a causal version of the adult data set in here [https://arxiv.org/pdf/1910.12586.pdf](https://arxiv.org/pdf/1910.12586.pdf)
