### ISSUE TITLE
Read the following papers

### ISSUE THREAD

**Issue by archanarw** [zenna/CounterfactualFairness.jl#19]
- [x] https://causalai.net/r37.pdf
- [x] https://ftp.cs.ucla.edu/pub/stat_ser/r321-L.pdf
- [x] https://arxiv.org/abs/1802.08139
- [x] https://www.ijcai.org/proceedings/2017/549

**Comment by mschauer** [comment]
Relatedly: I started adding the "Recanting witness criterion" from Avin, Shpitser, Pearl (paper 2, also paper 4) in https://github.com/mschauer/CausalInference.jl/pull/53 so we can test given a causal DAG,  but it's not so obvious how to get from the definition to an implementation... any input is welcome there.
