### ISSUE TITLE
Find appropriate datasets

### ISSUE THREAD

**Issue by zenna** [zenna/CounterfactualFairness.jl#4]
Find appropriate initial dataset to test counterfactual fairness.

**Comment by archanarw** [comment]
Can we use [Adult Dataset](http://archive.ics.uci.edu/ml/datasets/Adult)? It is mentioned [here](https://www.researchgate.net/publication/310673366_A_Causal_Framework_for_Discovering_and_Removing_Direct_and_Indirect_Discrimination), under "Experiments" section ,that they have used PC algorithm to find the causal network.

**Comment by mschauer** [comment]
Researchgate-free link: https://www.ijcai.org/proceedings/2017/549

**Comment by mschauer** [comment]
Yeah, good pick. They use it in Algorithm 1 (PSE-DD) in step 1 `G = buildCausalNetwork(D);`, but we can just take the data set and apply PC for a start to have a working example.
