### ISSUE TITLE
Draft blogpost

### ISSUE THREAD

**Issue by zenna** [zenna/CounterfactualFairness.jl#7]
Draft of blogpost for JSOC outlining project plans

**Comment by archanarw** [comment]
[https://nextjournal.com/a/P1YKkVy3j78zkurtyh8Jj?token=K4ZmM5cmwAykQ31y6hteqk
](https://nextjournal.com/a/P1YKkVy3j78zkurtyh8Jj?token=K4ZmM5cmwAykQ31y6hteqk
) Is this okay?

**Comment by mschauer** [comment]
Nice - this is how I imagined it.

**Comment by zenna** [comment]
Share this with the Julia J/GSOC organizers on slack
